name: Build LaTeX Document
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "example.tex"
          args: "-shell-escape -interaction=nonstopmode"
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4 
        with:
          name: latex-pdf
          path: example.pdf
          
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: example.pdf
          generate_release_notes: true
