name: Build and Upload LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "example.tex"
          args: "-shell-escape -interaction=nonstopmode"
          
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4 
        with:
          name: latex-pdf
          path: example.pdf
          
      - name: Commit and Push PDF
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add example.pdf
          git commit -m "Update PDF [skip ci]"
          git push
